name: CI

on:
  push:
  pull_request:
    branches: [dependabot/**]

jobs:
  client:
    name: Client
    runs-on: ubuntu-latest
    concurrency: ci-client-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Packages (Common)
        working-directory: ./common
        run: npm ci

      - name: Install Packages (Client)
        working-directory: ./client
        run: npm ci

      - name: Build
        working-directory: ./client
        run: npm run build
  server:
    name: Server
    runs-on: ubuntu-latest
    concurrency: ci-serveri-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Packages (Common)
        working-directory: ./common
        run: npm ci

      - name: Install Packages (Server)
        working-directory: ./server
        run: npm ci

      - name: Build
        working-directory: ./server
        run: npm run build
